@echo off
echo Compiling...
g++ %1.cpp -o %1 -lm -Wall -Wextra -O2 -std=c++20 -Wl,--stack=512000000 -I /Code/libs/ac-library -I /Code/libs/testlib -DLOCAL
echo Running...
%1.exe < .\sample\%1\%2.in > .\sample\%1\%2.out
echo Checking...
check .\sample\%1\%2.in .\sample\%1\%2.out .\sample\%1\%2.ans
del %1.exe